include:
  - local: "/gitlab-ci/includes.yml"

stages:
  - code-quality
  - code-analysis
  - open-source

variables:
  GITHUB_REPO_NAME: "forgerock-google-analytics-node"
  CI_PROJECT_NAME: "forgerock-google-analytics-node"
  # Config
  RULESET: MAVEN_CI
  BUILD_TYPE: MAVEN
  MVN_CLI_OPTS: "--batch-mode"
  MVN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_IMAGE: "maven:3-jdk-11"
  YQ_VERSION: "3.4.1"

open-source:
  stage: open-source
  when: manual
  only:
    refs:
      - tags
      - branches
