include:
  #code-quality
  - project: 'wa-transformation/pipeline-fragments/gitleaks'
    ref: 1-5-0
    file: 'ci-include-gitleaks.yml'
  - project: 'wa-transformation/pipeline-fragments/shell-check'
    ref: 2-1-0
    file: 'ci-include-shell-check.yml'
  - project: 'wa-transformation/pipeline-fragments/todo-checker'
    ref: 1-1-0
    file: 'ci-include-todo-checker.yml'
  - project: 'wa-transformation/pipeline-fragments/maven-checkstyle-lint'
    ref: 2-0-0
    file: 'ci-include-maven-checkstyle-lint.yml'
  - project: 'wa-transformation/pipeline-fragments/docker-lint'
    ref: 1-1-0
    file: 'ci-include-docker-lint.yml'
  #code-analysis
  # - project: 'wa-transformation/pipeline-fragments/maven-api-pitest'
  #   ref: 2-3-0
  #   file: 'ci-include-maven-api-pitest.yml'
  # - project: 'wa-transformation/pipeline-fragments/maven-api-spotbugs'
  #   ref: 2-3-0
  #   file: 'ci-include-maven-api-spotbugs.yml'
  # - project: 'wa-transformation/pipeline-fragments/sonarqube'
  #   ref: 3-2-0
  #   file: 'ci-include-sonar_scanner.yml'
  #open-sourcing
  - project: 'wa-transformation/pipeline-fragments/open-source'
    ref: 1-0-0
    file: 'ci-include-open-source.yml'
